name: docker-build-and-push

on:
  push:
    paths-ignore:
      - README.md
      - example-nginx-reverse-proxy.conf
      - .github/workflows/docker-update-description.yml
      - .github/dependabot.yml
    branches:
      - main

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: get package.json
        id: package_json
        run: |
          echo "PACKAGE_AUTHOR=$( npm view ./ author )" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: pabra/checkip
          labels: |
            org.opencontainers.image.authors=${{ steps.package_json.outputs.PACKAGE_AUTHOR }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=pabra/checkip:buildcache
          cache-to: type=registry,ref=pabra/checkip:buildcache,mode=max
